### ISSUE TITLE
Update all tests to set the environment variables that they require

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#251]
Currently, some tests explicitly specify the environment variables that will be needed and some tests assume that these variables are already set. Even if a target is added to the Makefile to set the required variables, we'd still have the case where someone is trying to run a test from the IDE or just using pytest and then the required variables would not be set.

We should likely update the tests so that they read the environment variables to be used from a file or something like that.

**Comment by fjuma** [comment]
We should also add assertions to the tests to make sure the required variables are set.

**Comment by kabir** [comment]
I'm working on this since I think it is useful for what I need to do next. Or at least they might be somewhat related.

I'm taking the approach that the user needs to set the variables before running the tests, and doing a coarse grained check that the main environment variables are set.

This is based on the .env file I have locally to run the tests

```
export POD_CONTAINER=docker
# export POD_CONTAINER=podman

# Env vars to configure Stomp
export STOMP_USER=artemis
export STOMP_PASSWORD=artemis
# Env vars to configure the Neo4j db. Currently, these values are hardcoded in the tests
export NEO4J_USERNAME=neo4j
export NEO4J_PASSWORD=neo4jpassword
export NEO4J_DATABASE=neo4j
# Env vars to configure the PgVector db. Currently, these values are hardcoded in the tests
export POSTGRES_USER=postgres
export POSTGRES_PASSWORD=postgres
export POSTGRES_DB=postgres
# Env vars for the model serving
export MODEL_PATH=/Users/kabir/sourcecontrol/python/models
export MODEL_NAME=Phi-3-mini-4k-instruct-q4.gguf
# Groq
export GROQ_API_KEY=XXXXXXXXXXXXXX
```

We could go more fine-grained, and only require the exact variables for each test, but I think that will be very fiddly and time consuming to get right
