### ISSUE TITLE
Tests for serialization and deserialization reference the abstract WiseAgent class

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#319]
We should update the YAML files used in these tests and the objects referenced in the tests to reference the actual WiseAgent implementations instead.

**Comment by kabir** [comment]
Just poking around to see if we can enforce not being able to instantiate it I tried:
```
import abc
class WiseAgent(yaml.YAMLObject, abc.ABC):

```

However that gives some metadata conflict, probably because both YAMLObject and ABC use those.

But I found https://stackoverflow.com/questions/7989042/preventing-a-class-from-direct-instantiation-in-python, and tried
```
class WiseAgent(yaml.YAMLObject):
    ''' A WiseAgent is an abstract class that represents an agent that can send and receive messages to and from other agents.
    '''
    yaml_tag = u'!wiseagents.WiseAgent'
    yaml_loader = WiseAgentsLoader

    def __new__(cls, *args, **kwargs):
        '''Create a new instance of the class, setting default values for the instance variables.'''
        if cls is WiseAgent:
            raise TypeError(f"only children of '{cls.__name__}' may be instantiated")
        obj = super().__new__(cls)
```
This seems to work better. A lot of agent tests pass, and it seems the ones where WiseAgent is instantiated directly fail as desired. 

I've not looked into the exact usages

**Comment by fjuma** [comment]
We'll likely need this in our other abstract classes as well.
